// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3824.Promobot.subsystems;

import org.usfirst.frc3824.Promobot.Constants;
import org.usfirst.frc3824.Promobot.Robot;
import org.usfirst.frc3824.Promobot.RobotMap;
import org.usfirst.frc3824.Promobot.commands.*;

import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.PIDController;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
 *
 */
public class CannonActuator extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController motor = RobotMap.cannonActuatorMotor;
    Encoder encoder = RobotMap.cannonActuatorEncoder;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    PIDController positionPID = new PIDController(
	        Constants.CANNON_ACTUATOR_POSITION_P,
	        Constants.CANNON_ACTUATOR_POSITION_I,
	        Constants.CANNON_ACTUATOR_POSITION_D, 
	        encoder, 
	        motor);
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
    public double getPosition()
	{
		return encoder.get();
	}
    
    public void resetEncoder()
	{
		encoder.reset();
	}
    
    public void setPositionSetpoint(double setpoint)
	{
		positionPID.setSetpoint(setpoint);
	}
    
    public boolean isPositionPIDEnabled()
	{
		return positionPID.isEnable();
	}
    
    public double getPositionSetpoint()
	{
		return positionPID.getSetpoint();
	}
    
    public void enablePositionPID()
	{
		positionPID.enable();
	}
    
    public double getError()
	{
		return positionPID.getError();
	}
	
	public double getOutput()
	{
		return motor.get();
	}
	
	public void resetPID()
	{
		positionPID.reset();
	}
	
	public void setContinuous()
	{
		positionPID.setContinuous();
	}
	
	public void setOutputRange()
	{
		positionPID.setOutputRange(-Constants.MOTOR_LIMIT, Constants.MOTOR_LIMIT);
	}
	
	public void setMotorPower(double motorPower)
	{
		motor.set(motorPower);
	}
}

