// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3824.Promobot.subsystems;

import org.usfirst.frc3824.Promobot.Robot;
import org.usfirst.frc3824.Promobot.RobotMap;
import org.usfirst.frc3824.Promobot.commands.*;

import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.Relay;
import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Cannons extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    Solenoid solenoid1 = RobotMap.cannonsSolenoid1;
    Solenoid solenoid2 = RobotMap.cannonsSolenoid2;
    Solenoid solenoid3 = RobotMap.cannonsSolenoid3;
    Solenoid solenoid4 = RobotMap.cannonsSolenoid4;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    boolean canFire;
    
   //Relay testSolenoid = RobotMap.cannonsTestSolenoid;
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
    public Solenoid getSolenoid1() {
    	
    	return solenoid1;
    	
    }
    
    public Solenoid getSolenoid2() {
    	
    	return solenoid2;
    	
    }
    
    public Solenoid getSolenoid3() {
    	
    	return solenoid3;
    	
    }
    
    public Solenoid getSolenoid4() {
    	
    	return solenoid4;
    	
    }
    
//    public boolean safetyLock() {
//    	
//    	if (Robot.humanSafetySensor.getBatSensor().getRangeInches() >= 108) {
//    		
//    		return false;
//    		
//    	}
//    	
//    	else {
//    		
//    		return true;
//    		
//    	}
//    	
//    }
}

